### PR TITLE
fix Deleting Queue Just after starting subscription causes channel error.

### LINKED ISSUE #50: Deleting Queue Just after starting subscription causes channel error.
Hi,

This is the test code.
```javascript
let rabbit = require("rabbot");
const settings = {
    connection: {
        user: "guest",
        pass: "guest",
        server: "127.0.0.1",
        heartbeat : 20,
        vhost : "testhost",
        replyQueue: false
    },
    exchanges:[
            { name: "test", type: "topic", persistent: true }
        ],
    logging: {
        adapters: {
            stdOut: {
                level: 6,
                bailIfDebug: true
            }
        }
    }
};

rabbit.configure( settings ).done( function() {
    console.log("Rabbot successfully configured");
    RunTest();
} );


function CreateAndListenQueue(routeKey,callback,state,tag = "")
{
    let queueName = `test.${routeKey}.${tag}`;
    let createPromise =  rabbit.addQueue(queueName,{durable:true,noAck:true,noBatch:true,autoDelete:true,expires:2 * 60 *1000});
    createPromise = createPromise.then(() => {
        return rabbit.bindQueue("test",queueName,routeKey);
    });
    createPromise = createPromise.then(() => {
        state.queueName = queueName;
        state.handler = rabbit.handle({
            queue: queueName, // only handle messages from the queue with this name
            type: "#", // handle messages with this type name or pattern
            autoNack: true, // automatically handle exceptions thrown in this handler
            context: state, // control what `this` is when invoking the handler
            handler: callback // allows you to just pass the handle function as an option property
        });
        state._queueStopped = false;
        state.CleanUp = function() {
            if(!this._queueStopped)
            {
                this._queueStopped = true;
                StopQueue(this.queueName, this.handler);
            }
        }.bind(state);

        return rabbit.startSubscription(queueName,true);
    });
    return createPromise;
}


function StopQueue(queue,handler)
{
    handler.remove();
    rabbit.deleteQueue(queue);
}

function testCallback(msg)
{

}

function RunTest()
{
    var state = {};
    let procedure =  CreateAndListenQueue(`test.msg`,testCallback,state);
    procedure.then(() => {
        //check if service exists, else delete the queue
       state.CleanUp();
    });
}
```

i get a channel error in rabbitmq saying _"operation basic.consume caused a channel exception not_found: "no queue 'test.test.msg.'"_.

it seems that startSubscription state machine is different from addQueue and deleteQueue, it happens on next tick, but then the queue that it is supposed to consume doesn't exist any more.

is this the correct way to do it.
is there a callback that we can listen on when startSubscription succeeds.
we cannot use stopSubscription because then i get a new error saying _"Potentially unhandled rejection [1] Error: No active subscription presently exists on the queue"_.

any thoughts?

regards

### PR DESCRIPTION
**Pull request by aankur**
startSubscription does not return a promise signifying subscription state.
this commit fixes #50

### CODE REVIEW

File: src/queueFsm.js [hunk 1]
```diff
@@ -74,13 +74,17 @@ var Factory = function( options, connection, topology, serializers, queueFn ) {
...
+			queue.subscribe( !!exclusive )
+			  .then(
+				onSubscribe,
+				function( err ) {
+				  emit( "subscribeFailed", err )
+				  reject("subscribeFailed " + err);
+				}
+			  )
+			  .then(resolve);
+		});
```
Comment (iamjochem) [inline src/queueFsm.js]: hi there,

no need to wrap this up in a `return when.promise( ... )` because `queue.subscribe` is already returning a promise, also `subscriber` does not reference `this` so I don't think there is a need to call `bind(this)` the following is (should be) functionally equivalent:

```js
var subscriber = function( exclusive ) {
  return queue.subscribe( !!exclusive ).then(onSubscribe).catch(function(err) { 
    emit( "subscribeFailed", err );
    throw err;
  });
};
```

Comment (aankur) [inline src/queueFsm.js]: Thanks for your insight, what was i thinking, updated the commit to reflect the changes

Comment (iamjochem) [inline src/queueFsm.js]: nice one :-)
